apiVersion: v1
kind: Service
metadata:
  name: locust-exporter
  namespace: monitoring
spec:
  selector:
    app: locust-exporter
  ports:
    - name: metrics
      port: 9646
      targetPort: 9646           # expose exporter port
  type: ClusterIP
