apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  namespace: monitoring
data:
  prometheus.yml: |-
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'nodejs-app'
        metrics_path: /metrics
        static_configs:
          - targets: ['sample-app3.default.svc.cluster.local:9091']

      - job_name: 'locust'
        metrics_path: /metrics
        static_configs:
          - targets: ['locust-exporter.monitoring.svc.cluster.local:9646']
